version: "3"

services:
  telzirfrontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - telzirmongo
      - telzirbackend

  telzirbackend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3000"
    depends_on:
      - telzirmongo
    environment:
      - MONGO_URL=mongodb://telzirmongo:27017/telzir

  telzirmongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./scripts/mongo:/docker-entrypoint-initdb.d
    expose:
      - "27017"
    environment:
      MONGO_INITDB_DATABASE: telzir